import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import ChoiceChip from '../components/ChoiceChip';
import { GOAL_OPTIONS } from '../services/profileService';
import { buildAntiZeroStats } from '../utils/behaviorAnalysis';

export default function HomeScreen({ events, goal, onGoalChange, flashMessage, onConsumption, onCraving, onTalk, onHistory, onAnalysis }) {
  const [editingGoal, setEditingGoal] = useState(!goal); const stats = buildAntiZeroStats(events); const goalLabel = GOAL_OPTIONS.find(({ value }) => value === goal)?.label;
  return <ScrollView style={styles.screen} contentContainerStyle={styles.container}>
    <Text style={styles.title}>Jour après Jour</Text><Text style={styles.subtitle}>Aujourd’hui, on fait quoi ?</Text>
    {!!flashMessage && <View style={styles.messageCard}><Text style={styles.messageText}>{flashMessage}</Text></View>}
    <View style={styles.goalCard}><View style={styles.goalHeader}><Text style={styles.goalTitle}>Mon objectif</Text>{goal && !editingGoal && <Pressable onPress={() => setEditingGoal(true)}><Text style={styles.change}>Modifier</Text></Pressable>}</View>
      {!editingGoal && goalLabel ? <Text style={styles.goalValue}>{goalLabel}</Text> : <><Text style={styles.goalHelper}>{goal ? 'Choisis ton nouvel objectif.' : 'Choisis ce qui te correspond aujourd’hui. Tu pourras le modifier.'}</Text><View style={styles.goalChoices}>{GOAL_OPTIONS.map((option) => <ChoiceChip key={option.value} label={option.label} selected={goal === option.value} onPress={() => { onGoalChange(option.value); setEditingGoal(false); }} />)}</View></>}
    </View>
    <Pressable style={styles.mainAction} onPress={onConsumption}><Text style={styles.mainActionTitle}>Enregistrer</Text><Text style={styles.mainActionSubtitle}>J’ai consommé</Text></Pressable>
    <Pressable style={styles.mainAction} onPress={onCraving}><Text style={styles.mainActionTitle}>J’ai une envie</Text><Text style={styles.mainActionSubtitle}>Faire le point sans avoir consommé</Text></Pressable>
    <Pressable style={styles.talkAction} onPress={onTalk}><Text style={styles.talkTitle}>Parler</Text><Text style={styles.talkSubtitle}>Comprendre ce qui se passe avec le compagnon Jour après Jour</Text><View style={styles.badge}><Text style={styles.badgeText}>Bientôt</Text></View></Pressable>
    <Text style={styles.sectionTitle}>Tes progrès, jour après jour</Text><View style={styles.statsGrid}><Stat value={`${stats.masteredDays7d}/7`} label="jours sans consommation enregistrée"/><Stat value={`${stats.masteredDays30d}/30`} label="jours sans consommation enregistrée"/><Stat value={stats.resistedCount30d} label="envies surmontées sur 30 jours"/><Stat value={stats.consumptionCount7d} label="consommations sur 7 jours"/></View>
    <View style={styles.evolution}><Text style={styles.evolutionText}>{stats.evolutionText}</Text></View>
    <Pressable style={styles.analysisButton} onPress={onAnalysis}><Text style={styles.analysisTitle}>Voir mes analyses</Text><Text style={styles.analysisSubtitle}>Découvrir les tendances de mes entrées locales</Text></Pressable>
    <Pressable style={styles.secondaryButton} onPress={onHistory}><Text style={styles.secondaryText}>Voir l’historique</Text></Pressable><StatusBar style="auto" />
  </ScrollView>;
}
function Stat({ value, label }) { return <View style={styles.statCard}><Text style={styles.statNumber}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#E8F5E9'},container:{flexGrow:1,paddingHorizontal:22,paddingTop:60,paddingBottom:70},title:{fontSize:32,fontWeight:'bold',color:'#2E7D32',textAlign:'center',marginBottom:10},subtitle:{fontSize:18,color:'#555',textAlign:'center',marginBottom:24},messageCard:{backgroundColor:'#FFF',borderRadius:14,padding:15,marginBottom:20,borderWidth:1,borderColor:'#C8E6C9'},messageText:{color:'#2E7D32',textAlign:'center',lineHeight:21},goalCard:{backgroundColor:'#FFF',borderRadius:14,padding:17,marginBottom:20,borderWidth:1,borderColor:'#C8E6C9'},goalHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},goalTitle:{fontSize:18,fontWeight:'bold',color:'#2E7D32'},change:{color:'#2E7D32',fontWeight:'600',padding:5},goalValue:{color:'#444',fontSize:16,marginTop:9},goalHelper:{color:'#555',lineHeight:20,marginTop:8,marginBottom:12},goalChoices:{flexDirection:'row',flexWrap:'wrap',gap:8},mainAction:{backgroundColor:'#2E7D32',borderRadius:18,padding:20,marginBottom:14},mainActionTitle:{color:'#FFF',fontSize:22,fontWeight:'bold'},mainActionSubtitle:{color:'#E8F5E9',marginTop:5,fontSize:14},talkAction:{backgroundColor:'#FFF',borderWidth:2,borderColor:'#2E7D32',borderRadius:18,padding:20,marginBottom:30},talkTitle:{color:'#2E7D32',fontSize:22,fontWeight:'bold'},talkSubtitle:{color:'#555',marginTop:5,lineHeight:20},badge:{alignSelf:'flex-start',marginTop:12,backgroundColor:'#E8F5E9',paddingHorizontal:10,paddingVertical:5,borderRadius:12},badgeText:{color:'#2E7D32',fontSize:12,fontWeight:'600'},sectionTitle:{fontSize:22,fontWeight:'bold',color:'#2E7D32',marginBottom:15},statsGrid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginBottom:12},statCard:{width:'48%',flexGrow:1,backgroundColor:'#FFF',borderRadius:14,padding:16,alignItems:'center',borderWidth:1,borderColor:'#C8E6C9'},statNumber:{fontSize:27,fontWeight:'bold',color:'#1B5E20'},statLabel:{fontSize:12,color:'#555',textAlign:'center',marginTop:5,lineHeight:16},evolution:{backgroundColor:'#FFF',borderRadius:12,padding:14,marginBottom:18,borderLeftWidth:4,borderLeftColor:'#66BB6A'},evolutionText:{color:'#2E7D32',lineHeight:20,fontWeight:'600'},analysisButton:{backgroundColor:'#1B5E20',borderRadius:14,padding:16,marginBottom:12},analysisTitle:{color:'#FFF',fontSize:17,fontWeight:'bold'},analysisSubtitle:{color:'#C8E6C9',fontSize:13,marginTop:4},secondaryButton:{borderWidth:1,borderColor:'#2E7D32',borderRadius:12,padding:14},secondaryText:{color:'#2E7D32',textAlign:'center',fontWeight:'600'}});
